### ISSUE TITLE
[Bug] Grayscale apps are inverted

### ISSUE THREAD

**Issue by doktersmith** [tahaak67/Farhan#35]
Hi! When I enable Grayscale, only whitelisted apps turn gray. Is it on purpose? I use the last version on F-Droid.

**Comment by tahaak67** [comment]
Yes its the intended behaivour,
When features like notifications filter is enabled the filter is applied to all applications excpect apps that are in the "Exceptions" list for the screen grayscale however Farhan uses a whitelist instead so that grayscale is only applied to apps added to the whitelist.

if you look at the grayscale settings screen you will see that the first option that enables the grayscale has a label that says "Enable grayscale for whitelisted apps"

**Comment by doktersmith** [comment]
I see. Thanks for the answer!

Em segunda-feira, 25 de setembro de 2023, Taha Ben Ashur <
***@***.***> escreveu:
